### ISSUE TITLE
Add me as a collaborator?

### ISSUE THREAD

**Issue by feross** [Flet/semistandard#242]
Hi @Flet, I was trying to push a change to preemptively fix the tests in this repo before `standard` 13 is released (and to avoid disabling testing the style of `semistandard` in the `standard` test suite). But I realized I have no push access. Lmk if you can add me! Thanks!

**Comment by Flet** [comment]
Done!

**Comment by feross** [comment]
Thanks @Flet!

**Comment by feross** [comment]
@Flet Actually, it looks like I still don't have push access to this repo or npm. Can you take another look?

**Comment by feross** [comment]
Oh, sorry. I forgot that GitHub changed things and you have to accept the invitation first. D'oh!

**Comment by Flet** [comment]
Ah, thanks for reminding me... added on npm as well.

**Comment by feross** [comment]
👍
